#!/bin/zsh
# This hook is run after every virtualenv is activated.

PS1="$_OLD_VIRTUAL_PS1"

cd () {
    if (( $# == 0 ))
    then
        proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
        cd ~/code/$proj_name        
    else
        builtin cd "$@"
    fi
}

cd

